name: Docker Build and Run

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: ls
        run: docker build -t my-docker-image -f Dockerfile .

      - name: Run Docker image
        run: |
          docker run my-docker-image
          export EXIT_CODE=$?

      - name: Set exit code
        run: exit $EXIT_CODE

  check-test-results:
    runs-on: ubuntu-latest
    needs: build-and-run

    steps:
      - name: Check test results
        run: exit ${{ needs.build-and-run.outputs['set-exit-code'] }}
