name: Run Automation Tests

# Controls when the action will run.
on:
  pull_request:
    types:
      - [opened, reopened, edited]

jobs:

  
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t mytest -f Dockerfile .

      - name: Push Docker Image
        run: docker run -it mytest